info:
  name: Update
  type: http
  seq: 2

http:
  method: PATCH
  url: "{{baseUrl}}/api/trips/00000000-0000-0000-0000-000000000000/tasks/00000000-0000-0000-0000-000000000000"
  body:
    type: json
    data: |-
      {
        "complete": true
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
