[test]
preload = ["./tests/preload.ts"]
coverage = false
coveragePathIgnorePatterns = [
  "**/*.test.ts",
  "tests/preload.ts",
  "generated/**/*"
]
coverageThreshold = 0.9

[serve.static]
env = "BUN_PUBLIC_*"
