include:
  - ./docker-compose.dev.yml

services:
  app:
    build:
      context: .
      target: prerelease
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/outpost
      - PORT=3000
      - SKIP_LOG_WRITE=true
      - BETTER_AUTH_SECRET=really-bad-secret
      - BETTER_AUTH_URL=http://localhost:3000
      - REDIS_URL=valkey://redis:6379
      - RESEND_API_KEY=not-a-real-key
