export const MOCK_LIST = {
  id: 1,
  name: "REI Backpacking Checklist",
  public: true,
  editable: false,
  sourceUrl: "https://www.rei.com/dam/backpacking_checklist_printable.pdf",
  description:
    "To determine what you need to bring on a backpacking trip, think about how far you plan to hike, how remote the location is and what the weather forecast has in store. This list is intentionally comprehensive and you won't take all items.",
  copiedFromPackingListId: null,
  sections: [
    {
      id: 1,
      name: "Backpacking Gear",
      sortPosition: 1,
      items: [
        {
          id: 1,
          name: "Backpack",
          optional: false,
          quantity: 2,
          sortPosition: 1,
        },
        {
          id: 2,
          name: "Backpacking tent",
          optional: false,
          quantity: 1,
          sortPosition: 2,
        },
        {
          id: 3,
          name: "Sleeping bag",
          optional: false,
          quantity: 1,
          sortPosition: 3,
        },
        {
          id: 4,
          name: "Sleeping pad",
          optional: false,
          quantity: 1,
          sortPosition: 4,
        },
        {
          id: 5,
          name: "Headlamp or flashlight (with extra batteries)",
          optional: false,
          quantity: 1,
          sortPosition: 5,
        },
        {
          id: 6,
          name: "Trekking poles",
          optional: true,
          quantity: 1,
          sortPosition: 6,
        },
        {
          id: 7,
          name: "Packable lantern",
          optional: true,
          quantity: 1,
          sortPosition: 7,
        },
        {
          id: 8,
          name: "Tent footprint",
          optional: true,
          quantity: 1,
          sortPosition: 8,
        },
        { id: 9, name: "Pillow", optional: true, quantity: 1, sortPosition: 9 },
        {
          id: 10,
          name: "Bear spray",
          optional: true,
          quantity: 1,
          sortPosition: 10,
        },
      ],
    },
    {
      id: 2,
      name: "Navigation",
      sortPosition: 2,
      items: [
        {
          id: 11,
          name: "Map (in waterproof sleeve)",
          optional: false,
          quantity: 1,
          sortPosition: 1,
        },
        {
          id: 12,
          name: "Compass",
          optional: false,
          quantity: 1,
          sortPosition: 2,
        },
        {
          id: 13,
          name: "Route description/guidebook",
          optional: true,
          quantity: 1,
          sortPosition: 3,
        },
        {
          id: 14,
          name: "Altimeter Watch",
          optional: true,
          quantity: 1,
          sortPosition: 4,
        },
        { id: 15, name: "GPS", optional: true, quantity: 1, sortPosition: 5 },
        {
          id: 16,
          name: "Satellite messenger and/or personal locator beacon",
          optional: true,
          quantity: 1,
          sortPosition: 6,
        },
      ],
    },
    {
      id: 3,
      name: "Clothing/Footwear",
      sortPosition: 3,
      items: [
        {
          id: 17,
          name: "Moisture-wicking underwear",
          optional: false,
          quantity: 1,
          sortPosition: 1,
        },
        {
          id: 18,
          name: "Moisture-wicking T-shirts",
          optional: false,
          quantity: 1,
          sortPosition: 2,
        },
        {
          id: 19,
          name: "Quick-drying pants/shorts",
          optional: false,
          quantity: 1,
          sortPosition: 3,
        },
        {
          id: 20,
          name: "Long-sleeve shirts (for sun and bugs)",
          optional: false,
          quantity: 1,
          sortPosition: 4,
        },
        {
          id: 21,
          name: "Lightweight fleece or jacket",
          optional: false,
          quantity: 1,
          sortPosition: 5,
        },
        {
          id: 22,
          name: "Boots or shoes suited to terrain",
          optional: false,
          quantity: 1,
          sortPosition: 6,
        },
        {
          id: 23,
          name: "Socks (synthetic or wool)",
          optional: false,
          quantity: 1,
          sortPosition: 7,
        },
        {
          id: 24,
          name: "Extra clothes (beyond the minimum expectation)",
          optional: false,
          quantity: 1,
          sortPosition: 8,
        },
        {
          id: 25,
          name: "Rainwear (jacket and pants)",
          optional: true,
          quantity: 1,
          sortPosition: 9,
        },
        {
          id: 26,
          name: "Long underwear",
          optional: true,
          quantity: 1,
          sortPosition: 10,
        },
        {
          id: 27,
          name: "Warm insulated jacket or vest",
          optional: true,
          quantity: 1,
          sortPosition: 11,
        },
        {
          id: 28,
          name: "Fleece pants",
          optional: true,
          quantity: 1,
          sortPosition: 12,
        },
        {
          id: 29,
          name: "Gloves or mittens",
          optional: true,
          quantity: 1,
          sortPosition: 13,
        },
        {
          id: 30,
          name: "Warm hat",
          optional: true,
          quantity: 1,
          sortPosition: 14,
        },
        {
          id: 31,
          name: "Sandals (for fording streams and/or camp shoes)",
          optional: true,
          quantity: 1,
          sortPosition: 15,
        },
        {
          id: 32,
          name: "Bandana or Buff",
          optional: true,
          quantity: 1,
          sortPosition: 16,
        },
        {
          id: 33,
          name: "Gaiters (for rainy, snowy, or muddy conditions)",
          optional: true,
          quantity: 1,
          sortPosition: 17,
        },
      ],
    },
    {
      id: 4,
      name: "Camp Kitchen",
      sortPosition: 4,
      items: [
        {
          id: 34,
          name: "Backpacking stove",
          optional: false,
          quantity: 1,
          sortPosition: 1,
        },
        { id: 35, name: "Fuel", optional: false, quantity: 1, sortPosition: 2 },
        {
          id: 36,
          name: "Cookset",
          optional: false,
          quantity: 1,
          sortPosition: 3,
        },
        {
          id: 37,
          name: "Dishes/bowls",
          optional: false,
          quantity: 1,
          sortPosition: 4,
        },
        {
          id: 38,
          name: "Eating utensils",
          optional: false,
          quantity: 1,
          sortPosition: 5,
        },
        {
          id: 39,
          name: "Mug/cup",
          optional: false,
          quantity: 1,
          sortPosition: 6,
        },
        {
          id: 40,
          name: "Biodegradable soap",
          optional: false,
          quantity: 1,
          sortPosition: 7,
        },
        {
          id: 41,
          name: "Small quick-dry towel",
          optional: false,
          quantity: 1,
          sortPosition: 8,
        },
        {
          id: 42,
          name: "Collapsible water container",
          optional: false,
          quantity: 1,
          sortPosition: 9,
        },
        {
          id: 43,
          name: "Bear canister/food sack; or hang bag + 50' nylon cord",
          optional: false,
          quantity: 1,
          sortPosition: 10,
        },
      ],
    },
    {
      id: 5,
      name: "Food & Water",
      sortPosition: 5,
      items: [
        {
          id: 44,
          name: "Water bottles and/or reservoir",
          optional: false,
          quantity: 1,
          sortPosition: 1,
        },
        {
          id: 45,
          name: "Water filter/purifier or chemical treatment",
          optional: false,
          quantity: 1,
          sortPosition: 2,
        },
        {
          id: 46,
          name: "Meals",
          optional: false,
          quantity: 1,
          sortPosition: 3,
        },
        {
          id: 47,
          name: "Energy food and drinks (bars, gels, chews, trail mix, drink mix)",
          optional: false,
          quantity: 1,
          sortPosition: 4,
        },
        {
          id: 48,
          name: "Extra day's supply of food",
          optional: false,
          quantity: 1,
          sortPosition: 5,
        },
      ],
    },
    {
      id: 6,
      name: "Health & Hygiene",
      sortPosition: 6,
      items: [
        {
          id: 49,
          name: "Hand sanitizer",
          optional: false,
          quantity: 1,
          sortPosition: 1,
        },
        {
          id: 50,
          name: "Toothbrush and toothpaste",
          optional: false,
          quantity: 1,
          sortPosition: 2,
        },
        {
          id: 51,
          name: "Sanitation trowel",
          optional: false,
          quantity: 1,
          sortPosition: 3,
        },
        {
          id: 52,
          name: "Toilet paper/wipes and sealable bag (to pack it out)",
          optional: false,
          quantity: 1,
          sortPosition: 4,
        },
        {
          id: 53,
          name: "Menstrual products",
          optional: false,
          quantity: 1,
          sortPosition: 5,
        },
        {
          id: 54,
          name: "Prescription medications",
          optional: false,
          quantity: 1,
          sortPosition: 6,
        },
        {
          id: 55,
          name: "Prescription glasses",
          optional: false,
          quantity: 1,
          sortPosition: 7,
        },
        {
          id: 56,
          name: "Sunglasses (+ retainer leash)",
          optional: false,
          quantity: 1,
          sortPosition: 8,
        },
        {
          id: 57,
          name: "Sunscreen",
          optional: false,
          quantity: 1,
          sortPosition: 9,
        },
        {
          id: 58,
          name: "SPF-rated lip balm",
          optional: false,
          quantity: 1,
          sortPosition: 10,
        },
        {
          id: 59,
          name: "Sun hat",
          optional: false,
          quantity: 1,
          sortPosition: 11,
        },
        {
          id: 60,
          name: "Insect repellent",
          optional: true,
          quantity: 1,
          sortPosition: 12,
        },
        {
          id: 61,
          name: "Urinary products",
          optional: true,
          quantity: 1,
          sortPosition: 13,
        },
        {
          id: 62,
          name: "Additional blister treatment supplies",
          optional: true,
          quantity: 1,
          sortPosition: 14,
        },
      ],
    },
    {
      id: 7,
      name: "Tools & Repairs",
      sortPosition: 7,
      items: [
        {
          id: 63,
          name: "Knife or multi-tool",
          optional: false,
          quantity: 1,
          sortPosition: 1,
        },
        {
          id: 64,
          name: "Repair kit for mattress, stove",
          optional: false,
          quantity: 1,
          sortPosition: 2,
        },
        {
          id: 65,
          name: "Duct tape strips",
          optional: false,
          quantity: 1,
          sortPosition: 3,
        },
      ],
    },
    {
      id: 8,
      name: "Emergency Items",
      sortPosition: 8,
      items: [
        {
          id: 66,
          name: "First-aid kit or supplies",
          optional: false,
          quantity: 1,
          sortPosition: 1,
        },
        {
          id: 67,
          name: "Whistle",
          optional: false,
          quantity: 1,
          sortPosition: 2,
        },
        {
          id: 68,
          name: "Lighter/matches (in waterproof container)",
          optional: false,
          quantity: 1,
          sortPosition: 3,
        },
        {
          id: 69,
          name: "Fire starter (for emergency survival fire)",
          optional: false,
          quantity: 1,
          sortPosition: 4,
        },
        {
          id: 70,
          name: "Emergency shelter",
          optional: false,
          quantity: 1,
          sortPosition: 5,
        },
        {
          id: 71,
          name: "Two itineraries: 1 left with friend + 1 under car seat",
          optional: false,
          quantity: 1,
          sortPosition: 6,
        },
      ],
    },
    {
      id: 9,
      name: "Personal Items",
      sortPosition: 9,
      items: [
        {
          id: 81,
          name: "Permits (if needed)",
          optional: false,
          quantity: 1,
          sortPosition: 1,
        },
        {
          id: 82,
          name: "Credit card and/or cash",
          optional: false,
          quantity: 1,
          sortPosition: 2,
        },
        { id: 83, name: "ID", optional: false, quantity: 1, sortPosition: 3 },
        {
          id: 84,
          name: "Car keys",
          optional: false,
          quantity: 1,
          sortPosition: 4,
        },
        {
          id: 85,
          name: "Cellphone",
          optional: false,
          quantity: 1,
          sortPosition: 5,
        },
      ],
    },
    {
      id: 10,
      name: "Backpacking Extras",
      sortPosition: 10,
      items: [
        {
          id: 72,
          name: "Daypack (for day trips away from camp)",
          optional: true,
          quantity: 1,
          sortPosition: 1,
        },
        {
          id: 73,
          name: "Camera or action cam (with extra memory cards)",
          optional: true,
          quantity: 1,
          sortPosition: 2,
        },
        {
          id: 74,
          name: "Interpretive field guide(s)",
          optional: true,
          quantity: 1,
          sortPosition: 3,
        },
        {
          id: 75,
          name: "Star chart/night-sky identifier",
          optional: true,
          quantity: 1,
          sortPosition: 4,
        },
        {
          id: 76,
          name: "Outdoor journal or sketchbook with pen/pencil",
          optional: true,
          quantity: 1,
          sortPosition: 5,
        },
        {
          id: 77,
          name: "Book/reading material",
          optional: true,
          quantity: 1,
          sortPosition: 6,
        },
        {
          id: 78,
          name: "Cards or games",
          optional: true,
          quantity: 1,
          sortPosition: 7,
        },
        {
          id: 79,
          name: "Compact binoculars",
          optional: true,
          quantity: 1,
          sortPosition: 8,
        },
        {
          id: 80,
          name: "Two-way radios",
          optional: true,
          quantity: 1,
          sortPosition: 9,
        },
      ],
    },
  ],
};
