import { db } from "$/utils/db";
import type { ProductionSeed } from "./production-seed";

async function run() {
  const categories = [
    "Backpacks",
    "Bear Proof Containers",
    "Bear Safety",
    "Bidets",
    "Bivies",
    "Bowls",
    "Bug Protection",
    "Carabiners",
    "Chairs",
    "Clothing",
    "Coats",
    "Cordage",
    "Crampons",
    "Cutting Boards",
    "Dog Gear",
    "Drinks",
    "Dry Bags",
    "Fanny Packs",
    "Fire Starters",
    "Flashlights",
    "Food Bags",
    "Footprints",
    "Fuel Accessories",
    "Gaiters",
    "Gear Lofts",
    "Gear Maintenance & Repair",
    "Gloves",
    "GPS",
    "Hammocks",
    "Hats",
    "Headlamps",
    "Hip Pockets",
    "Hoods",
    "Hygiene",
    "First Aid",
    "Ice Axes",
    "Inclinometers",
    "Jackets",
    "Knives",
    "Multitools",
    "Lanterns",
    "Lighters",
    "Liners",
    "Microspikes",
    "Mugs",
    "Navigation Tools",
    "Neckwear",
    "Notebooks",
    "Optics",
    "Pack Covers",
    "Pack Liners",
    "Pack Organization",
    "Packrafts",
    "Pillows",
    "Plastic Containers",
    "Plates",
    "Pouches",
    "Pots",
    "Power Banks",
    "Quilts",
    "Rain Gear",
    "Sandals",
    "Shelters",
    "Shoes",
    "Shoulder Pockets",
    "Sit Pads",
    "Sleepwear",
    "Sleeping Bags",
    "Sleeping Bag Liners",
    "Sleeping Pads",
    "Sleeping Pad Inflators",
    "Smartwatches",
    "Snowshoes",
    "Soaps",
    "Socks",
    "Stakes",
    "Stoves",
    "Stuff Sacks",
    "Sun Protection",
    "Sunglasses",
    "Tables",
    "Tarps",
    "Tents",
    "Toothbrushes",
    "Toothpaste",
    "Towels",
    "Trekking Poles",
    "Trowels",
    "Umbrellas",
    "Utensils",
    "Wallets",
    "Water Containers",
    "Water Filters",
    "Water Purifiers",
    "Water Treatments",
    "Whistles",
    "Wipes",
    "Writing Utensils",
  ];

  // Proof-of-concept keyword coverage for BTP-143's item-name-based category
  // suggestions. Extending coverage later is a data change here, not code --
  // see suggestCategories in app/utils/search-helpers.ts.
  const categoryKeywords: Record<string, string[]> = {
    Tents: ["tent"],
    Backpacks: ["backpack", "rucksack"],
    "Sleeping Bags": ["sleeping bag"],
    "Sleeping Pads": ["sleeping pad"],
    "Water Filters": ["water filter", "filter"],
    Stoves: ["stove", "burner"],
    Headlamps: ["headlamp"],
    "Trekking Poles": ["trekking pole"],
  };

  await db.gearCategory.createMany({
    data: categories.map((name) => ({
      name,
      public: true,
      keywords: categoryKeywords[name] ?? [],
    })),
  });
}

export const publicGearCategories: ProductionSeed = {
  run,
  name: "public-gear-categories",
};
